In [12]:
from __future__ import division
from fuzzywuzzy import fuzz
import numpy as np
import scipy
from scipy.spatial import distance
# from sklearn.cluster import DBSCAN

In [7]:
coords = [(0, 0), (1, 1)]
distance.cdist(coords, coords, 'euclidean')

array([[ 0.        ,  1.41421356],
       [ 1.41421356,  0.        ]])

In [11]:
coords = [(0, 0), (1, 1)]
d = distance.pdist(coords, 'euclidean')
print d
s = distance.squareform(d)
print s

[ 1.41421356]
[[ 0.          1.41421356]
 [ 1.41421356  0.        ]]


In [13]:
def fuzzy_distance(string1, string2, partial=False):
    if partial:
        distance_func = fuzz.partial_token_set_ratio
    else:
        distance_func = fuzz.token_set_ratio
    distance = 1 - distance_func(string1, string2) / 100
    return distance

In [30]:
data = ['Hello', 'world', 'peace', 'Java', 'Python']
indices = np.arange(len(data)).reshape(-1,1)
distance.cdist(indices, indices, lambda a_idx, b_idx: fuzzy_distance(data[int(a_idx[0])], data[int(b_idx[0])]))

array([[ 0.  ,  0.8 ,  0.8 ,  1.  ,  0.64],
       [ 0.8 ,  0.  ,  1.  ,  1.  ,  0.82],
       [ 0.8 ,  1.  ,  0.  ,  0.78,  0.82],
       [ 1.  ,  1.  ,  0.78,  0.  ,  1.  ],
       [ 0.64,  0.82,  0.82,  1.  ,  0.  ]])

In [ ]:
class DistanceMatrix(object):
    def __init__(self, items, distance_function):
        self._items = items
        self._distance_function = distance_function
        self._distances = 

    
    def get_distance(self, i, j):
        pass

In [38]:
matrix = np.arange(100).reshape(10, -1)
ixgrid = np.ix_([0,1], [0,1])
print matrix
print matrix[ixgrid]
# print matrix[[0,1,2], [5,4,2]]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0  1]
 [10 11]]


In [ ]:
x = 123